[package]
name = "fredRuntime"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.9", features = ["lua54", "vendored"] }
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
walkdir = "2.4"
winres = "0.1"

[[bin]]
name = "fred"
path = "src/main.rs"

[build-dependencies]
winres = "0.1"
