[package]
name = "fredRuntime"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.9", features = ["lua54", "vendored"] }
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading", "Win32_Foundation"] }

[[bin]]
name = "fred"
path = "src/main.rs"